[DEFAULT]
# Format:
# LeftClass=RightClass:field_left=field_right,field_left2=field_right2
CreateUserRequest=UserDao:username=username,role=role
CreateAccountResponse=AccountDao:accountNumber=account_number,balance=balance
DepositMoneyResponse=TransactionDao:id=account_id,balance=amount
UpdateProfileResponse=UserDao:id=id,username=username,name=name,role=role
TransferMoneyResponse=TransactionDao:senderAccountId=account_id,receiverAccountId=related_account_id,amount=amount