# Format: RequestClass=ResponseClass:field_request_1=field_response_1,field_request_2=field_response_2
[DEFAULT]
CreateUserRequest=CreateUserResponse:username=username,role=role
LoginUserRequest=LoginUserResponse:username=username
Transaction=Transaction:id=id,amount=amount,type=type,relatedAccountId=relatedAccountId
TransferMoneyResponse=TransferMoneyResponse:status=status,message=message,amount=amount,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,fraudRiskScore=fraudRiskScore,fraudReason=fraudReason,requiresManualReview=requiresManualReview,requiresVerification=requiresVerification
FraudCheckStatusResponse=FraudCheckStatusResponse:status=status,note=note,transactionId=transactionId